name: Standard Library Function Request
description: Request a new function for the standard library
labels: ["enhancement", "stdlib"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new standard library function!

        **Students:** If you're a student, please remember to contact us directly (on Slack, etc.) for a small prize!

  - type: input
    id: name
    attributes:
      label: Function Name
      description: What should the function be called?
      placeholder: e.g., zipWith, takeWhile, intercalate
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Target Module
      description: Which standard library module should this function belong to?
      options:
        - prelude
        - list
        - io
        - bool
        - maybe
        - either
        - New module (specify below)
    validations:
      required: true

  - type: input
    id: new_module
    attributes:
      label: New Module Name
      description: If you selected "New module" above, what should it be called?

  - type: textarea
    id: signature
    attributes:
      label: Type Signature
      description: What should the type signature be?
      placeholder: |
        ```stlcpp
        zipWith : forall a b c. (a -> b -> c) -> List a -> List b -> List c
        ```
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what the function does.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: If you have an implementation in mind, share it here.
      placeholder: |
        ```stlcpp
        zipWith f xs ys = case xs of
          | Nil -> Nil
          | Cons x xs' -> case ys of
            | Nil -> Nil
            | Cons y ys' -> Cons (f x y) (zipWith f xs' ys')
        ```

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how the function would be used.
      placeholder: |
        ```stlcpp
        zipWith (+) [1, 2, 3] [4, 5, 6]  -- Result: [5, 7, 9]
        ```

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this function useful? What use cases does it enable?
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to similar functions in other languages (Haskell, OCaml, etc.)
